// src/ChatbotPage.jsx
import { useState, useEffect, useRef } from "react";

const welcome_msg =
`Thank you for agreeing to take part in this research study. We'll walk you through the study procedure. Taking part is voluntary and you can stop using the chatbot at any time.
At each step you can choose to continue to the next step, get more information, or ask a question. All response content is generated by a large language model.`

function ChatbotPage({ onBack, session }) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [displayIndex, setDisplayIndex] = useState(0);
  const [pulseProgress, setPulseProgress] = useState(false);
  const [pulsePage, setPulsePage] = useState(false);
  const [messages, setMessages] = useState(() => [
    {
      id: `bot-${currentIndex}`,
      sender: "bot",
      text: welcome_msg,
      title: "Welcome",
    },
  ]);

  // declare session ID early instead of per function
  const sessionId = session?.session_id
  const totalSteps = 12 // eventually this will be pulled from API instead of hardcoded.

  function checkMessage(type) {
    // returns number of messages per step and type (free/more)
    let matches = 0
    // iterate over messages
    for (const m of messages) {
      // get first (chars) places of message ID - will be (role)-(index)-(type)
      if (m?.id.slice(0,11) === `user-${currentIndex}-${type}`) {
        // increment match count for each valid result
        matches++
      }
    }
    // return count. Will be 0 for first message of each unique role/step/type combination, then increment.
    return matches
  }

  async function getChatbotResponse(qid, rid, content) {
    try {
      const response = await fetch(
        `http://localhost:5174/api/session/${sessionId}/chat`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ qid, rid, content }),
        }
      );
      const output = await response.json()
      return output.message
    } catch (e) {
      return "Something went wrong. Please try again."
    }
  }

  const handleNext = async () => {
    // can't skip to next step while chatbot response pending
    if (isLoading) return;
    
    if (currentIndex < totalSteps + 1) {
      const nextIndex = currentIndex + 1;
      const query_id = `user-${nextIndex}`
      const response_id = `bot-${nextIndex}`


      setMessages((prev) => [
        ...prev,
        {
          id: query_id,
          sender: "user",
          text: "Okay, got it – next step.",
        }
      ]);

      setIsLoading(true);
      showTyping();

      setDisplayIndex(nextIndex);
      setPulseProgress(true);
      setPulsePage(true);
      setTimeout(() => setPulseProgress(false), 520);
      setTimeout(() => setPulsePage(false), 520);

      const response = await getChatbotResponse(query_id, response_id,"NEXT STEP")
      setCurrentIndex(nextIndex);

      setMessages((prev) => [
        ...prev,
        {
          id: response_id,
          sender: "bot",
          title: `Step ${nextIndex}`,
          text: response,
        }
      ]);

      hideTyping();
      setIsLoading(false);

    }
  };

  // Get the most recent non-typing bot message so "More info" expands the right thing
  const getLastBotMessage = () => {
    for (let i = messages.length - 1; i >= 0; i--) {
      const m = messages[i];
      if (m?.sender === "bot" && !m.isTyping) return m;
    }
    return null;
  };

  const handleMoreInfo = async () => {
    // stop spam clicks
    if (isLoading) return;
    if (!sessionId) return;

    // Find what we’re expanding (last bot message in the chat)
    const lastBot = getLastBotMessage();
    if (!lastBot) return;

    // Show the user’s request in chat immediately
    const msg_count = checkMessage("more")
    const query_id = `user-${currentIndex}-more-${msg_count}`
    const response_id = `bot-${currentIndex}-more-${msg_count}`

    setMessages((prev) => [
      ...prev,
      {
        id: query_id,
        sender: "user",
        text: "Tell me more",
      },
    ]);

    setIsLoading(true);
    showTyping();

    const response = await getChatbotResponse(query_id, response_id, "MORE INFO")

    // Add the model's "more info" response
    setMessages((prev) => [
      ...prev,
      {        
        id: response_id,
        sender: "bot",
        title: `Step ${currentIndex} - More Info`,
        text: response,
      },
      ]);
    
    hideTyping();
    setIsLoading(false);
  
  };

  // Added loading state + typing message id ref
  const [isLoading, setIsLoading] = useState(false);
  const typingIdRef = useRef(null);

  // func to  show typing message
  const showTyping = () => {
    const typingId = `bot-typing-${Date.now()}`;
    typingIdRef.current = typingId;

    setMessages((prev) => [
      ...prev,
      {
        id: typingId,
        sender: "bot",
        text: "TYPING_INDICATOR", // Special marker for animated dots
        isTyping: true,
      },
    ]);
  };

  // func to remove typing message
  const hideTyping = () => {
    const typingId = typingIdRef.current;
    if (!typingId) return;

    setMessages((prev) => prev.filter((m) => m.id !== typingId));
    typingIdRef.current = null;
  };


  const handleFreeText = async () => {
    
    //added this to stop spamming
    if (isLoading) return;
    if (!sessionId) return;

    //turning on typing UI
    const textbox = document.getElementById("freeTextInput");
    const content = textbox.value;
    // added this heree to clear input field automatically
    textbox.value = "";

    const msg_count = checkMessage("free")
    const query_id = `user-${currentIndex}-free-${msg_count}`
    const response_id = `bot-${currentIndex}-free-${msg_count}`

    // render query before sending 
    setMessages((prev) => [
      ...prev,
      {
        id: query_id,
        sender: "user",
        text: content,
      },
    ]);

    setIsLoading(true);
    showTyping();
      
    const response = await getChatbotResponse(query_id, response_id, content);

    setMessages((prev) => [
      ...prev,
      {
        id: response_id,
        sender: "bot",
        title: `Step ${currentIndex} - User Query`,
        text: response,
      },
    ]);

    // Always remove the typing bubble and re-enable the Go button.
    // This runs whether the request succeeds or fails.
    hideTyping();
    setIsLoading(false);
  };

  const atEnd = currentIndex === totalSteps;
  // const lastSavedIndexRef = useRef(0);

  const bottomRef = useRef(null);

  // moved logging to backend, all happens under single /api/session/.../chat endpoint

  useEffect(() => {
      bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  //added this to handle enter key press in input field
  const handleInputKeyDown = (event) => {
    if (event.key === "Enter") {
      event.preventDefault();
      handleFreeText();
    }
  };

  return (
    <div className={`chat-page${pulsePage ? " page-pulse" : ""}`}>
      <div className={`progress-bar-container${pulseProgress ? " pulse" : ""}`}>
        <div
          className="progress-bar"
          style={{ width: `${((displayIndex + 1) / totalSteps) * 100}%` }}
        />
      </div>
      <header className="chat-header">
        <button className="link-button" type="button" onClick={onBack}>
          ← Back to information
        </button>
        <div className="chat-title-block">
          <h1 className="chat-title">Chat assistant</h1>
          <p className="chat-subtitle">
            We’ll walk through the instructions step by step.
          </p>
        </div>
        <div className="progress">
          Step {currentIndex + 1} of {totalSteps}
        </div>
      </header>

      <main className="chat-layout">
        <section className="chat-window">
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={
                msg.sender === "bot" ? "message message-bot" : "message message-user"
              }
            >
              {msg.title && <div className="message-title">{msg.title}</div>}
              <p className="message-text">
                {msg.isTyping ? (
                  <>
                    
                    <span className="typing-indicator">
                      <span className="typing-dot"></span>
                      <span className="typing-dot"></span>
                      <span className="typing-dot"></span>
                    </span>
                  </>
                ) : (
                  msg.text.split("\n").map((line, idx) => (
                    <span key={idx}>
                      {line}
                      <br />
                    </span>
                  ))
                )}
              </p>
            </div>
          ))}
          <div ref={bottomRef} />
        </section>

        <section className="chat-controls">
          <div className="input-row">
            <input
              className="text-input"
              type="text"
              placeholder="Ask a question"
              id="freeTextInput"
              onKeyDown={handleInputKeyDown}
              //added disabled when loading 
              disabled={isLoading}

            />
           <button className="chip" type="button"
             onClick={handleFreeText} 
             disabled={isLoading}>
            {isLoading ? "…" : "Go"}
           </button>

          </div>          

          {!atEnd ? (
            <div className="quick-replies">
              <button className="chip" type="button" onClick={handleNext}>
                 Continue to Next Step
              </button>
              <button className="chip" type="button" onClick={handleMoreInfo}>
                 Get More Information
              </button>
            </div>
          ) : (
            <div className="end-actions">
              <div className="confetti" aria-hidden="true">
                {Array.from({ length: 22 }).map((_, i) => (
                  <span key={i} className={`confetti-piece confetti-${i % 6}`} />
                ))}
              </div>
              <p className="end-text">
                You’ve reached the end of the onboarding instructions.
              </p>
              <a
                className="primary-button"
                href="/participant-instruction-leaflet.pdf"
                download
              >
                Download instructions as PDF
              </a>
              <p className="small-note">
                {" "}
                <code></code> 
              </p>
            </div>
          )}

          
        </section>
      </main>
    </div>
  );
}

export default ChatbotPage;
